### 수정
PUT http://localhost:8080/users/marco
Content-Type: application/json

{
  "name": "뭘봐",
  "gender": "M",
  "age" : 30
}

### 등록
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "marco",
  "name": "마르코",
  "gender": "M",
  "age" : 30
}